// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MockProbe.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MockProbe.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260524084644_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MockProbe.Domain.Ai.AnswerEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("ModelRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_run_id");

                    b.Property<decimal?>("OverallScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("overall_score");

                    b.Property<string>("RawResult")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_result");

                    b.PrimitiveCollection<string[]>("RecommendedTopics")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("recommended_topics");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("status");

                    b.PrimitiveCollection<string[]>("Strengths")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("strengths");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserAnswerId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_answer_id");

                    b.PrimitiveCollection<string[]>("Weaknesses")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("weaknesses");

                    b.HasKey("Id")
                        .HasName("pk_answer_evaluations");

                    b.HasIndex("ModelRunId")
                        .HasDatabaseName("ix_answer_evaluations_model_run_id");

                    b.HasIndex("UserAnswerId")
                        .HasDatabaseName("ix_answer_evaluations_user_answer_id");

                    b.ToTable("answer_evaluations", "ai");
                });

            modelBuilder.Entity("MockProbe.Domain.Ai.AnswerEvaluationScore", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnswerEvaluationId")
                        .HasColumnType("uuid")
                        .HasColumnName("answer_evaluation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("MaxScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("max_score");

                    b.Property<string>("Rationale")
                        .HasColumnType("text")
                        .HasColumnName("rationale");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("score");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_answer_evaluation_scores");

                    b.HasIndex("AnswerEvaluationId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ix_answer_evaluation_scores_answer_evaluation_id_type");

                    b.ToTable("answer_evaluation_scores", "ai");
                });

            modelBuilder.Entity("MockProbe.Domain.Ai.ModelRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("integer")
                        .HasColumnName("completion_tokens");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("model_name");

                    b.Property<Guid?>("PracticeSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("practice_session_id");

                    b.Property<Guid?>("PromptTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("prompt_template_id");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_tokens");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("provider");

                    b.Property<string>("RequestPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("request_payload");

                    b.Property<string>("ResponsePayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_payload");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_model_runs");

                    b.HasIndex("PracticeSessionId")
                        .HasDatabaseName("ix_model_runs_practice_session_id");

                    b.HasIndex("PromptTemplateId")
                        .HasDatabaseName("ix_model_runs_prompt_template_id");

                    b.ToTable("model_runs", "ai");
                });

            modelBuilder.Entity("MockProbe.Domain.Ai.PromptTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<string>("TemplateText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Variables")
                        .HasColumnType("jsonb")
                        .HasColumnName("variables");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_prompt_templates");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_prompt_templates_key");

                    b.ToTable("prompt_templates", "ai");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Default conversational interviewer prompt.",
                            IsActive = true,
                            Key = "default_interviewer",
                            Name = "Default Interviewer",
                            TemplateText = "You are a focused mock interviewer helping a user practice. Ask one question at a time.",
                            Type = "Interviewer",
                            Variables = "{\"variables\":[\"session\",\"question\"]}",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Default answer scoring prompt.",
                            IsActive = true,
                            Key = "default_answer_evaluation",
                            Name = "Default Answer Evaluation",
                            TemplateText = "Evaluate the user's answer for relevance, clarity, depth, structure, and communication.",
                            Type = "AnswerEvaluation",
                            Variables = "{\"variables\":[\"question\",\"answer\"]}",
                            Version = 1
                        });
                });

            modelBuilder.Entity("MockProbe.Domain.Ai.SessionEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("ModelRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_run_id");

                    b.Property<decimal?>("OverallScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("overall_score");

                    b.Property<Guid>("PracticeSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("practice_session_id");

                    b.Property<string>("RawResult")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_result");

                    b.PrimitiveCollection<string[]>("RecommendedTopics")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("recommended_topics");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("status");

                    b.PrimitiveCollection<string[]>("Strengths")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("strengths");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.PrimitiveCollection<string[]>("Weaknesses")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("weaknesses");

                    b.HasKey("Id")
                        .HasName("pk_session_evaluations");

                    b.HasIndex("ModelRunId")
                        .HasDatabaseName("ix_session_evaluations_model_run_id");

                    b.HasIndex("PracticeSessionId")
                        .IsUnique()
                        .HasDatabaseName("ix_session_evaluations_practice_session_id");

                    b.ToTable("session_evaluations", "ai");
                });

            modelBuilder.Entity("MockProbe.Domain.Community.CommunityVote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VoteType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("vote_type");

                    b.HasKey("Id")
                        .HasName("pk_community_votes");

                    b.HasIndex("UserId", "EntityType", "EntityId")
                        .IsUnique()
                        .HasDatabaseName("ix_community_votes_user_id_entity_type_entity_id");

                    b.ToTable("community_votes", "community");
                });

            modelBuilder.Entity("MockProbe.Domain.Community.UserBookmark", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_bookmarks");

                    b.HasIndex("UserId", "EntityType", "EntityId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_bookmarks_user_id_entity_type_entity_id");

                    b.ToTable("user_bookmarks", "community");
                });

            modelBuilder.Entity("MockProbe.Domain.Identity.GuestSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConvertedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("converted_at");

                    b.Property<Guid?>("ConvertedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("converted_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("SessionTokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("session_token_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_guest_sessions");

                    b.HasIndex("SessionTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_guest_sessions_session_token_hash");

                    b.ToTable("guest_sessions", "identity");
                });

            modelBuilder.Entity("MockProbe.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("auth_provider");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalSubject")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("external_subject");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsSystemUser")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_user");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("role");

                    b.Property<string>("Settings")
                        .HasColumnType("jsonb")
                        .HasColumnName("settings");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email")
                        .HasFilter("email IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            AuthProvider = "None",
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "local@interview-practice.local",
                            FullName = "Local User",
                            IsSystemUser = true,
                            Role = "Admin",
                            Settings = "{}",
                            Status = "Active",
                            Username = "local"
                        });
                });

            modelBuilder.Entity("MockProbe.Domain.Identity.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("bio");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<string>("ExperienceLevel")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("experience_level");

                    b.Property<string>("PreferredLanguage")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("preferred_language");

                    b.Property<string>("Settings")
                        .HasColumnType("jsonb")
                        .HasColumnName("settings");

                    b.PrimitiveCollection<string[]>("Skills")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("skills");

                    b.Property<string>("TargetRole")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("target_role");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_profiles");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_profiles_user_id");

                    b.ToTable("user_profiles", "identity");
                });

            modelBuilder.Entity("MockProbe.Domain.Interview.JobDescription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("company_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DescriptionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_text");

                    b.Property<string>("ParsedJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("parsed_json");

                    b.PrimitiveCollection<string[]>("Skills")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("skills");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("source_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_job_descriptions");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_job_descriptions_user_id_created_at");

                    b.ToTable("job_descriptions", "interview");
                });

            modelBuilder.Entity("MockProbe.Domain.Interview.PracticeSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("InterviewTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("interview_template_id");

                    b.Property<Guid?>("JobDescriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_description_id");

                    b.Property<Guid?>("ResumeId")
                        .HasColumnType("uuid")
                        .HasColumnName("resume_id");

                    b.Property<string>("Settings")
                        .HasColumnType("jsonb")
                        .HasColumnName("settings");

                    b.Property<string>("ShareToken")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("share_token");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_practice_sessions");

                    b.HasIndex("ShareToken")
                        .IsUnique()
                        .HasDatabaseName("ix_practice_sessions_share_token")
                        .HasFilter("share_token IS NOT NULL");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_practice_sessions_user_id_created_at");

                    b.ToTable("practice_sessions", "interview");
                });

            modelBuilder.Entity("MockProbe.Domain.Interview.Resume", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("FileAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_asset_id");

                    b.Property<string>("ParsedJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("parsed_json");

                    b.Property<string>("RawText")
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.PrimitiveCollection<string[]>("Skills")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("skills");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("source_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_resumes");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_resumes_user_id_created_at");

                    b.ToTable("resumes", "interview");
                });

            modelBuilder.Entity("MockProbe.Domain.Interview.SessionMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid>("PracticeSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("practice_session_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("role");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_number");

                    b.Property<Guid?>("SessionQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_question_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_session_messages");

                    b.HasIndex("PracticeSessionId", "SequenceNumber")
                        .HasDatabaseName("ix_session_messages_practice_session_id_sequence_number");

                    b.ToTable("session_messages", "interview");
                });

            modelBuilder.Entity("MockProbe.Domain.Interview.SessionQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AskedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("asked_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("PracticeSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("practice_session_id");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt");

                    b.Property<Guid?>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_session_questions");

                    b.HasIndex("PracticeSessionId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ix_session_questions_practice_session_id_position");

                    b.ToTable("session_questions", "interview");
                });

            modelBuilder.Entity("MockProbe.Domain.Interview.UserAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer_text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("PracticeSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("practice_session_id");

                    b.Property<Guid>("SessionQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_question_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_user_answers");

                    b.HasIndex("PracticeSessionId")
                        .HasDatabaseName("ix_user_answers_practice_session_id");

                    b.HasIndex("SessionQuestionId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_answers_session_question_id");

                    b.ToTable("user_answers", "interview");
                });

            modelBuilder.Entity("MockProbe.Domain.QuestionBank.InterviewTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("difficulty");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<string>("Settings")
                        .HasColumnType("jsonb")
                        .HasColumnName("settings");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("status");

                    b.Property<string>("TargetRole")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("target_role");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_interview_templates");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_interview_templates_slug");

                    b.ToTable("interview_templates", "question_bank");

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "A balanced starter practice session for self-hosted mock interviews.",
                            Difficulty = "Intermediate",
                            IsPublic = true,
                            Name = "General Mock Interview",
                            Settings = "{}",
                            Slug = "general-mock-interview",
                            Status = "Published",
                            TargetRole = "Software Engineer"
                        });
                });

            modelBuilder.Entity("MockProbe.Domain.QuestionBank.InterviewTemplateQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("InterviewTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("interview_template_id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_interview_template_questions");

                    b.HasIndex("InterviewTemplateId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ix_interview_template_questions_interview_template_id_position");

                    b.ToTable("interview_template_questions", "question_bank");

                    b.HasData(
                        new
                        {
                            Id = new Guid("41000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            InterviewTemplateId = new Guid("40000000-0000-0000-0000-000000000001"),
                            IsRequired = true,
                            Position = 1,
                            QuestionId = new Guid("30000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("41000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            InterviewTemplateId = new Guid("40000000-0000-0000-0000-000000000001"),
                            IsRequired = true,
                            Position = 2,
                            QuestionId = new Guid("30000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("41000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            InterviewTemplateId = new Guid("40000000-0000-0000-0000-000000000001"),
                            IsRequired = false,
                            Position = 3,
                            QuestionId = new Guid("30000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("MockProbe.Domain.QuestionBank.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("difficulty");

                    b.Property<string>("Guidance")
                        .HasColumnType("text")
                        .HasColumnName("guidance");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_questions");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_questions_category_id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_questions_created_by_user_id");

                    b.ToTable("questions", "question_bank");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Difficulty = "Beginner",
                            IsPublic = true,
                            Metadata = "{}",
                            Prompt = "Give a concise overview of your background, strengths, and what you are looking to practice.",
                            Title = "Tell me about yourself",
                            Type = "Behavioral"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Difficulty = "Intermediate",
                            IsPublic = true,
                            Metadata = "{}",
                            Prompt = "Walk through a difficult bug, how you isolated it, and what you changed to prevent it from recurring.",
                            Title = "Describe a difficult bug you fixed",
                            Type = "Technical"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Difficulty = "Advanced",
                            IsPublic = true,
                            Metadata = "{}",
                            Prompt = "Design an API that supports mock interview sessions, answer storage, and asynchronous AI evaluation.",
                            Title = "Design a scalable interview practice API",
                            Type = "SystemDesign"
                        });
                });

            modelBuilder.Entity("MockProbe.Domain.QuestionBank.QuestionCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_category_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_question_categories");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_question_categories_slug");

                    b.ToTable("question_categories", "question_bank");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Communication, collaboration, and experience questions.",
                            Name = "Behavioral",
                            Slug = "behavioral",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Practical engineering and problem-solving questions.",
                            Name = "Technical",
                            Slug = "technical",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Architecture and tradeoff discussion questions.",
                            Name = "System Design",
                            Slug = "system-design",
                            SortOrder = 30
                        });
                });

            modelBuilder.Entity("MockProbe.Domain.QuestionBank.QuestionSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_question_skills");

                    b.HasIndex("QuestionId", "SkillId")
                        .IsUnique()
                        .HasDatabaseName("ix_question_skills_question_id_skill_id");

                    b.ToTable("question_skills", "question_bank");

                    b.HasData(
                        new
                        {
                            Id = new Guid("31000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            QuestionId = new Guid("30000000-0000-0000-0000-000000000001"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Weight = 3
                        },
                        new
                        {
                            Id = new Guid("31000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            QuestionId = new Guid("30000000-0000-0000-0000-000000000002"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000002"),
                            Weight = 3
                        },
                        new
                        {
                            Id = new Guid("31000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            QuestionId = new Guid("30000000-0000-0000-0000-000000000003"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000003"),
                            Weight = 3
                        });
                });

            modelBuilder.Entity("MockProbe.Domain.QuestionBank.QuestionTag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_question_tags");

                    b.HasIndex("QuestionId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_question_tags_question_id_slug");

                    b.ToTable("question_tags", "question_bank");
                });

            modelBuilder.Entity("MockProbe.Domain.QuestionBank.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_skills");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_skills_name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_skills_slug");

                    b.ToTable("skills", "question_bank");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Clear, structured verbal answers.",
                            Name = "Communication",
                            Slug = "communication"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Debugging, reasoning, and decision-making.",
                            Name = "Problem Solving",
                            Slug = "problem-solving"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Designing reliable and scalable systems.",
                            Name = "System Design",
                            Slug = "system-design"
                        });
                });

            modelBuilder.Entity("MockProbe.Domain.Storage.FileAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChecksumSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("checksum_sha256");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("kind");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("original_file_name");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("status");

                    b.Property<string>("StorageBucket")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("storage_bucket");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("storage_key");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_file_assets");

                    b.HasIndex("StorageBucket", "StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ix_file_assets_storage_bucket_storage_key");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_file_assets_user_id_created_at");

                    b.ToTable("file_assets", "storage");
                });

            modelBuilder.Entity("MockProbe.Domain.System.AppSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean")
                        .HasColumnName("is_secret");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("value_type");

                    b.HasKey("Id")
                        .HasName("pk_app_settings");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_app_settings_key");

                    b.ToTable("app_settings", "system");
                });
#pragma warning restore 612, 618
        }
    }
}
